### ISSUE TITLE
Read only permission for Global tenant

### ISSUE THREAD

**Issue by alesnav** [floragunncom/search-guard-module-kibana-multitenancy#6]
Hello there!

Is it possible to give Read Only permissions to one specific user for the Global tenant?

Normal users shouldn't have permissions to add/edit/delete visualizations nor dashboards, at least in our environment.

Thanks!

**Comment by jochenkressin** [comment]
The Global tenant is equal to the original Kibana index. We implemented it this way so that your already created dashboards and visualizations are still accessible after installing the MT module.

If you want to give a user RO permissions, you can configure that in the sg_role.yml for that user. Just give the user read permissions for the .kibana index.

The beta of the plugin will still show "read/write" for the global tenant though, should be fixed in the final release.

We will probably also release another beta version of the plugin prior to the final release. We've added:

- customization of the login page (use your own logo, title etc.)
- You can disable the private and/or global tenant
- The tenant selection is stored per user, so you don't need to switch after each login

If you need/want other features or enhancements: Now's a good time to tell us ;)

**Comment by alesnav** [comment]
Ok, @jochenkressin thanks for clarification.

Those enhancements sound very good for me. I'll be waiting for the next release! 👍 

Once published, I'll close this issue, based on the "read/write" bug when it is "read only"

Thanks!

**Comment by floragunn** [comment]
Release is scheduled for Tue 18th April

**Comment by floragunn** [comment]
@alesnav released today. If this issue is not resolved for you with todays release pls. open a new issue here https://github.com/floragunncom/search-guard-kibana-plugin/issues
